### ISSUE TITLE
Sphynx  or MkDocs for documentation?

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/sparklink#9]
see e.g. https://news.ycombinator.com/item?id=17717295

Leaning on side of Sphynx with docs written in markdown

**Comment by mamonu** [comment]
sphinx in my opinion too.

**Comment by mamonu** [comment]
ok have done a first draft. will create a pull request

**Comment by mamonu** [comment]
in order to do this i consulted the 3 following docs

https://www.sphinx-doc.org/en/master/index.html
https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html

with the help of `An idiot’s guide to Python documentation with Sphinx and ReadTheDocs`

https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/



TLDR
the file to edit for configuring sphinx is `conf.py` in the docs\source directory

**Comment by mamonu** [comment]
added also `!docs/*` on .gitignore as otherwise the build part of the docs is not saved.

**Comment by mamonu** [comment]
integrating markdown a bit better 
based on:

http://www.sphinx-doc.org/en/master/usage/markdown.html

and 

https://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst

**Comment by mamonu** [comment]
This is a nice way to think about the documentation of sparklink:
with autodoc the API will always be documented but it will be the *reference* part and we will need to think about the rest

![doc1](https://user-images.githubusercontent.com/3820011/71809983-2c3b3b00-3069-11ea-84e1-1d246ccb5d68.png)

**Comment by RobinL** [comment]
Closed by #22
